//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4206
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rui.FolderWatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rui.FolderWatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon AccessDeny {
            get {
                object obj = ResourceManager.GetObject("AccessDeny", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlsoTime {
            get {
                return ResourceManager.GetString("AlsoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ内の情報取得中 - {0:#,##0}個の項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderInfoMessage {
            get {
                return ResourceManager.GetString("FolderInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FromToDate {
            get {
                return ResourceManager.GetString("FromToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HoursFormat {
            get {
                return ResourceManager.GetString("HoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinutesFormat {
            get {
                return ResourceManager.GetString("MinutesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のフォルダは存在しないか、フォルダではないため情報を表示することが出来ませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFoundOpenFolder {
            get {
                return ResourceManager.GetString("NotFoundOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestTimeTitle {
            get {
                return ResourceManager.GetString("RestTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SecondsFormat {
            get {
                return ResourceManager.GetString("SecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectDisplayDirectory {
            get {
                return ResourceManager.GetString("SelectDisplayDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}個の項目を選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectItemsMessage {
            get {
                return ResourceManager.GetString("SelectItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnKown {
            get {
                return ResourceManager.GetString("UnKown", resourceCulture);
            }
        }
    }
}
